project:
  type: website
  output-dir: docs

website:
  title: "STA 9750 Submission Material"
 navbar:
 left:
   -text: "introduction"
    file: index.qmd
   -text: "MP01"
    file: mp01.qmd
   -text: "mp02"
    file: mp02.qmd
