project:
  type: website
  output-dir: docs

website:
  title: "STA 9750 Submission Material"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Mp01.qmd
        text: Payroll
      - href: MP02.qmd
        text: Transit Awards

format:
  html:
    theme: cosmo
    toc: true
