project:
  type: website

website:
  title: "🚇📉 Remote Work vs. Ridership: NYC’s Great Subway Shift"
  page-navigation: true
  sidebar: true       # ✅ enables visible navigation menu on the left
  navbar: false       # ✅ disables site-wide navigation tabs

format:
  html:
    theme:
      light: litera
    css: styles.css
    toc: true
    toc-title: "🧭 Explore Sections"
    code-overflow: wrap         # ✅ ensures code stays visible and readable
    code-copy: true             # ✅ adds copy button to code blocks
    code-line-numbers: true     # ✅ adds line numbers
    code-fold: true             # ✅ enables folding of code chunks
    code-tools:
      source: true
      toggle: true
      caption: none
